version: 2.1
workflows:
  deploying:
    jobs:
      - build
jobs:
  build:
    machine: true
    resource_class: nazzim29/circle_runner
    # docker:
    #   - image: node:12.7-alpine
    parallelism: 1
    working_directory: /var/vost-admin
    steps:
      - checkout
      - attach_workspace:
          at: /var/vost-admin
      - restore_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: chmod -R a+x node_modules
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: dist